openapi: 3.0.0
info:
  description: This is a API documentation for verification_service
  version: "1.0.0"
  title: Verification Service API
tags:
  - name: verifiable_documents
    description: Verifiable Document Calls
paths:
  /verifiable_documents:
    post:
      tags:
        - verifiable_documents
      summary: Verify a document
      operationId: addInventory
      responses:
        '200':
          description: File is valid
          content:
            application/json:
              examples:
                  verified_valid_document:
                    summary: verified_valid_document
                    value:
                      message: File is valid.
                  invalid_recipient:
                    summary: invalid_recipient
                    value:
                      status_code: invalid_recipient
                      error:
                        recipient.name:
                          value: ["The recipient.name must be provided with recipient.email"]
                  invalid_issuer:
                    summary: invalid_issuer
                    value:
                      status_code: invalid_issuer
                      error:
                        issuer.identityProof:
                          value: ["The file does not have a valid identityProof key."]
                  invalid_signature:
                    summary: invalid_signature
                    value:
                      status_code: invalid_signature
                      error:
                        signature.targetHash:
                          value: ["The file does not have a valid signature."]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                  nullable: false
            examples:
              data:
                $ref: '#/components/examples/data'
            encoding:
              file:
                style: form
        description: Inventory item to add
components:
  schemas:
    VerifiableDocumentFileContent:
      type: object
      required:
        - data
        - signature
      properties:
        data:
          $ref: '#/components/schemas/Data'
        signature:
          $ref: '#/components/schemas/Signature'
    Data:
      required:
        - name
        - recipient
        - issuer
      properties:
        id:
          type: string
          example: 63c79bd9303530645d1cca00
        name:
          type: string
          example: Certificate of Completion
        recipient:
          type: object
          properties:
            name:
              type: string
              example: Marty McFly
            email:
              type: string
              example: marty.mcfly@gmail.com
        issuer:
          type: object
          required:
            - name
            - identityProof
          properties:
            name:
              type: string
              example: Accredify
            identityProof:
              type: object
              properties:
                type:
                  type: string
                  example: DNS-DID
                key:
                  type: string
                  example: did:ethr:0x05b642ff12a4ae545357d82ba4f786f3aed84214#controller
                location:
                  type: string
                  example: ropstore.accredify.io
        issued:
          type: string
          example: "2022-12-23T00:00:00+08:00"
      type: object
    Signature:
      required:
        - targetHash
      properties:
        type:
          type: string
          example: SHA3MerkleProof
        targetHash:
          type: string
          example: 288f94aadadf486cfdad84b9f4305f7d51eac62db18376d48180cc1dd2047a0e
      type: object
  examples:
    data:
      value:
        id: "63c79bd9303530645d1cca00"
